repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: 
          - types-python-dateutil
          - psycopg[binary]
          - pgvector
          - python-dateutil
        args: ["--strict", "cns_py"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check (unit tests only)
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["-q", "--tb=short", "--maxfail=1", "-m", "not integration", "--ignore=tests/test_contradiction_integration.py", "--ignore=tests/test_cql_executor.py", "--ignore=tests/test_demo_query.py"]
